[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "tmp"
version = "0.1.2"
authors = [
  { name="msoconnor", email="msoconnor2@wisc.edu" },
]
description = "Tutorial"
readme = "README.md"
requires-python = ">=3.10"

