[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "source"
authors = [{name = "msoconnor", email = "tmp@g"}]
dynamic = ["version", "description"]

